---
controller:
  kind: Deployment
  allowSnippetAnnotations: true
  service:
    internal:
      enable: false
      # annotations:
      #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
